### ISSUE TITLE
Install fails on node v0.12.0

### ISSUE THREAD

**Issue by robertolicious** [ryanflorence/ember-tools#123]
**Environment**

```
$ node -v
v0.12.0
$ npm -v
2.5.1
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.9.3
BuildVersion:   13D65
```

**Install log**

```
$ npm install -g ember-tools

> sync-prompt@0.4.1 install /usr/local/lib/node_modules/ember-tools/node_modules/sync-prompt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/sync_prompt/src/sync_prompt.o
../src/sync_prompt.cc:33:18: error: variable has incomplete type 'struct termios'
  struct termios tty;
                 ^
../src/sync_prompt.cc:33:10: note: forward declaration of 'termios'
  struct termios tty;
         ^
../src/sync_prompt.cc:36:21: error: use of undeclared identifier 'ECHO'
    tty.c_lflag &= ~ECHO;
                    ^
../src/sync_prompt.cc:38:20: error: use of undeclared identifier 'ECHO'
    tty.c_lflag |= ECHO;
                   ^
../src/sync_prompt.cc:40:34: error: use of undeclared identifier 'TCSANOW'
  (void) tcsetattr(STDIN_FILENO, TCSANOW, &tty);
                                 ^
4 errors generated.
make: *** [Release/obj.target/sync_prompt/src/sync_prompt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ember-tools/node_modules/sync-prompt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 13.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ember-tools"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! sync-prompt@0.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sync-prompt@0.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sync-prompt package,
```

It appears that `sync-prompt` is broken, and their repo has not been updated in the last 8 months, I'd say project is inactive and should be dropped as a dependency.

**Comment by fivetanley** [comment]
Hey there, just a heads up: neither ryan or me are maintaining this project anymore. Ember CLI is the recommended approach forward from the Ember core team and is a much more active project with a more active ecosystem.

I've added a note to the README if anyone is interested in picking up maintainership.
